### ISSUE TITLE
Would you be willing to use the tag feature to create a downloadable copy of a specific release?

### ISSUE THREAD

**Issue by hwpplayer1** [nCine/ncline#1]
Thank you for creating ncline  and releasing it as free software. Because it is free software, I would like to add ncline to the Free Software Foundation's Free Software Directory (FSD). What is preventing me from doing so is the FSD's requirement to review a specific version of a given project. The best way for us to review a specific version is if a project uses the tag feature of github. Would you be willing to use the tag feature to create a downloadable copy of a specific release?

[0]: https://directory.fsf.org/

Thank you for your consideration.

**Comment by encelo** [comment]
Hello @hwpplayer1, I moved away from GitHub releases as it is too much work for me at the moment. I like to keep a "_always production ready_" policy for the `master` branch instead.
Can't you submit to the FSD a specific commit insteaad? 🤔 
 Let me know if you have different options and thanks for considering `ncline` for the addition. 😊

**Comment by hwpplayer1** [comment]
Hi @encelo We will study your project next Friday. Now I need to wait for other admins in the FSD. Thanks for your quick reply. See you.

**Comment by hwpplayer1** [comment]
@encelo  Thank you for the suggestion on creating a link to a specific commit, but I am not sure I know how to do this where the code base for the commit is easily accessible. Can you help me out?

**Comment by encelo** [comment]
Have a look at the list of all [commits](https://github.com/nCine/ncline/commits/master/) on the `master` branch and get a link to one of them, I suggest the [last one](https://github.com/nCine/ncline/tree/3ddf743d2d2fb632b9c060cad02f8dea3b605a11).

**Comment by hwpplayer1** [comment]
@encelo Thanks for your contribution. We have been added your project to Free Software Foundation's Directory [https://directory.fsf.org/wiki/Ncline](https://directory.fsf.org/wiki/Ncline)

**Comment by encelo** [comment]
@hwpplayer1 Thank you for adding it to the directory! 🙏🏻
